- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: present
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
  - name: Copy file with owner and permissions
    copy:
      src: /home/ec2-user/index.html
      dest: /var/www/html/index.html
      mode: '777'