- hosts: jenkins
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Add repository jenkins
    yum_repository:
      name: jenkins
      description: jen YUM repo
      baseurl: http://pkg.jenkins.io/redhat-stable
      gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  - name: install the latest version of java & jenkins
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - java
      - jenkins 
  - name: Start service jenkins, if not started
    service:
      name: jenkins
      state: started