- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  - name: install the latest version of Tools
    yum:
      name: "{{item}}"
      state: present
    loop:
      - php
      - mysql
      - unzip
      - http_present