- hosts: jenkins
  remote_user: ec2-user
  become: yes
  vars:
    ports: 8383
  tasks:
  - name: Add repository jenkins
    yum_repository:
      name: jenkins
      description: jen YUM repo
      baseurl: http://pkg.jenkins.io/redhat-stable
      gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  - name: install the latest version of java & jenkins
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - java
      - jenkins 
  - name: Changing ansible port no
    lineinfile:
      path: /usr/lib/systemd/system/jenkins.service
      regexp: Environment="JENKINS_PORT='
      line: Environment="JENKINS_PORT={{ports}}
    notify: restart jenkins 
  -handler:
  - name: Start service jenkins, if not started
    service:
      name: jenkins
      state: started
      shell: systemctl daemon-reload
  - name: restart jenkins
    service:
      name: jenkins
      state: restarted